### ISSUE TITLE
Moving to this repo

### ISSUE THREAD

**Issue by Skeyelab** [SmashingDashboard/smashing#18]
I started my project using dashing.  Is there an easy way to update my codebase to this one?

**Comment by kinow** [comment]
Good question @Skeyelab 

If there is nothing in the docs, we can use this issue to help you updating your codebase, and also create the initial documentation.

As an initial polite guess, what about `gem install smashing`, `smashing new $NAME_OF_YOUR_PROJECT`, and then copy your jobs, dashboards, etc?

**Comment by Skeyelab** [comment]
I considered that. I didnt know if there was a better way.  Possibly changing where .git/config is pointing.

**Comment by tylermauthe** [comment]
We should definitely make a wiki page for this.

I haven't tested this, but I think all you have to do is update your project's gemfile to point to smashing instead of dashing and then run bundle to reinstall your vendor gems. Then bundle exec smashing should work... If you're using the global command line tool, you'll need to do a gem install smashing before you can do smashing start.

**Comment by kinow** [comment]
It worked for me. I had a working dashboard, written with Dashing. Replaced dashing by smashing in my Gemfile, then run bundle install, saw smashing in the list of gems installed.

Starting the dashboard with `smashing s` successfully started the thin server. Jobs running happily too.

**Comment by kinow** [comment]
Has any approach worked for you @Skeyelab ?

**Comment by howardsternisbatman** [comment]
this also worked OK for me.

**Comment by kinow** [comment]
Thanks @howardsternisbatman 

Closing the ticket, but feel free to provide any feedback here @Skeyelab & others :-)
